export default {
  AUTH_REFRESH: "AUTH_REFRESH",
  AUTH_ACTION_LOGIN: "AUTH_ACTION_LOGIN",
  AUTH_ACTION_REGISTER: "AUTH_ACTION_REGISTER",
  AUTH_ACTION_REQUEST: "AUTH_ACTION_REQUEST",
  AUTH_ACTION_SUCCESS: "AUTH_ACTION_SUCCESS",
  AUTH_ACTION_ERROR: "AUTH_ACTION_ERROR",
  ASIDE_TOGGLE: "ASIDE_TOGGLE",
};
