export default {
  AUTH_REFRESH: "AUTH_REFRESH",
  AUTH_ACTION_LOGIN: "AUTH_ACTION_LOGIN",
  AUTH_ACTION_REGISTER: "AUTH_ACTION_REGISTER",
  AUTH_ACTION_REQUEST: "AUTH_ACTION_REQUEST",
  AUTH_ACTION_SUCCESS: "AUTH_ACTION_SUCCESS",
  AUTH_ACTION_ERROR: "AUTH_ACTION_ERROR",
  AUTH_ACTION_CLEAR: "AUTH_ACTION_CLEAR",
  AUTH_ACTION_CLEAR_ERROR: "AUTH_ACTION_CLEAR_ERROR",
  CLEAR_STORE: "CLEAR_STORE",

  ASIDE_TOGGLE: "ASIDE_TOGGLE",

  INGRIDIENTS_ACTION_GET: "INGRIDIENTS_ACTION_GET",
  INGRIDIENTS_ACTION_POST: "INGRIDIENTS_ACTION_POST",
  INGRIDIENTS_ACTION_UPDATE: "INGRIDIENTS_ACTION_UPDATE",
  INGRIDIENTS_ACTION_REMOVE: "INGRIDIENTS_ACTION_REMOVE",

  INGRIDIENTS_ACTION_GET_REQUEST: "INGRIDIENTS_ACTION_GET_REQUEST",
  INGRIDIENTS_ACTION_POST_REQUEST: "INGRIDIENTS_ACTION_POST_REQUEST",
  INGRIDIENTS_ACTION_UPDATE_REQUEST: "INGRIDIENTS_ACTION_UPDATE_REQUEST",
  INGRIDIENTS_ACTION_REMOVE_REQUEST: "INGRIDIENTS_ACTION_REMOVE_REQUEST",

  INGRIDIENTS_ACTION_GET_SUCCESS: "INGRIDIENTS_ACTION_GET_SUCCESS",
  INGRIDIENTS_ACTION_POST_SUCCESS: "INGRIDIENTS_ACTION_POST_SUCCESS",
  INGRIDIENTS_ACTION_UPDATE_SUCCESS: "INGRIDIENTS_ACTION_UPDATE_SUCCESS",
  INGRIDIENTS_ACTION_REMOVE_SUCCESS: "INGRIDIENTS_ACTION_REMOVE_SUCCESS",

  INGRIDIENTS_ACTION_GET_ERROR: "INGRIDIENTS_ACTION_GET_ERROR",
  INGRIDIENTS_ACTION_POST_ERROR: "INGRIDIENTS_ACTION_POST_ERROR",
  INGRIDIENTS_ACTION_UPDATE_ERROR: "INGRIDIENTS_ACTION_UPDATE_ERROR",
  INGRIDIENTS_ACTION_REMOVE_ERROR: "INGRIDIENTS_ACTION_REMOVE_ERROR",

  PRODUCTS_ACTION_GET: "PRODUCTS_ACTION_GET",
  PRODUCTS_ACTION_POST: "PRODUCTS_ACTION_POST",
  PRODUCTS_ACTION_UPDATE: "PRODUCTS_ACTION_UPDATE",
  PRODUCTS_ACTION_REMOVE: "PRODUCTS_ACTION_REMOVE",

  PRODUCTS_ACTION_GET_REQUEST: "PRODUCTS_ACTION_GET_REQUEST",
  PRODUCTS_ACTION_POST_REQUEST: "PRODUCTS_ACTION_POST_REQUEST",
  PRODUCTS_ACTION_UPDATE_REQUEST: "PRODUCTS_ACTION_UPDATE_REQUEST",
  PRODUCTS_ACTION_REMOVE_REQUEST: "PRODUCTS_ACTION_REMOVE_REQUEST",

  PRODUCTS_ACTION_GET_SUCCESS: "PRODUCTS_ACTION_GET_SUCCESS",
  PRODUCTS_ACTION_POST_SUCCESS: "PRODUCTS_ACTION_POST_SUCCESS",
  PRODUCTS_ACTION_UPDATE_SUCCESS: "PRODUCTS_ACTION_UPDATE_SUCCESS",
  PRODUCTS_ACTION_REMOVE_SUCCESS: "PRODUCTS_ACTION_REMOVE_SUCCESS",

  PRODUCTS_ACTION_GET_ERROR: "PRODUCTS_ACTION_GET_ERROR",
  PRODUCTS_ACTION_POST_ERROR: "PRODUCTS_ACTION_POST_ERROR",
  PRODUCTS_ACTION_UPDATE_ERROR: "PRODUCTS_ACTION_UPDATE_ERROR",
  PRODUCTS_ACTION_REMOVE_ERROR: "PRODUCTS_ACTION_REMOVE_ERROR",
};
