const {
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_TIME,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_TIME
} = process.env

module.exports = {
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_TIME,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_TIME
}
